# By default, builds only for darwin and linux, which works for us since FlowGo does not support
# Windows builds. We also can only build on amd64 architectures since all others are also not
# supported at the moment.
builds:
  - id: archive-client
    binary: archive-client
    main: ./cmd/flow-archive-client
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=relic

  - id: archive-indexer
    binary: archive-indexer
    main: ./cmd/flow-archive-indexer
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=relic

  - id: archive-server
    binary: archive-server
    main: ./cmd/flow-archive-server
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=relic

  - id: archive-live
    binary: archive-live
    main: ./cmd/flow-archive-live
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=relic

archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
